#!/usr/bin/env python3
"""Injecte des questions de quiz (cf. spec §4.4) dans public/books/atomic-habits.json.

4 questions par carte, ancrées sur le contenu. Les id sont générés au format
<cardId>-qN. Idempotent : remplace toute clé "questions" existante.
"""
import json
from pathlib import Path

# Pour chaque carte (par numéro d'ordre), 4 questions : (énoncé, [4 choix], index bonne réponse, explication)
Q = {
1: [
 ("Que montre l'histoire de l'accident de baseball de James Clear ?",
  ["Qu'une reconstruction faite de petites routines répétées mène à de grands résultats",
   "Qu'un talent inné finit toujours par se révéler",
   "Qu'un changement radical et soudain a tout sauvé",
   "Que la motivation seule suffit à se relever"], 0,
  "Sa remontée vient de gestes modestes (sommeil, organisation, musculation) accumulés sur des années."),
 ("D'où naissent les transformations durables selon ce chapitre ?",
  ["D'un exploit ponctuel et spectaculaire",
   "De l'accumulation patiente de gestes minuscules constants",
   "D'un coup de chance bien saisi",
   "D'une motivation exceptionnelle"], 1,
  "C'est la constance de petits gestes, pas l'intensité d'un instant, qui change tout."),
 ("Que signifie le mot « atomique » dans « habitudes atomiques » ?",
  ["Explosif et puissant",
   "Complexe et scientifique",
   "À la fois minuscule et unité de base d'un système plus grand",
   "Rare et précieux"], 2,
  "Une habitude atomique est toute petite mais sert de brique à un système puissant."),
 ("Comment ce chapitre suggère-t-il de démarrer ?",
  ["En visant tout de suite un objectif ambitieux",
   "En attendant d'être motivé",
   "En changeant tout d'un coup",
   "En choisissant une habitude si petite qu'elle paraît ridicule"], 3,
  "Une amorce minuscule ne crée pas de résistance et peut être tenue dans la durée."),
],
2: [
 ("Que devient-on en s'améliorant de 1 % par jour pendant un an ?",
  ["Environ 37 fois meilleur",
   "Environ 2 fois meilleur",
   "Environ 10 fois meilleur",
   "À peine meilleur"], 0,
  "1,01^365 ≈ 37 : l'effet cumulatif est énorme."),
 ("Qu'est-ce que le « plateau du potentiel latent » (vallée de la déception) ?",
  ["Le moment où l'on a atteint son maximum",
   "La période où les efforts ne donnent pas encore de résultats visibles",
   "Une phase de régression inévitable",
   "Le sommet d'une habitude"], 1,
  "Les progrès s'accumulent en coulisses avant de devenir visibles, comme un glaçon qui fond par paliers."),
 ("Que faut-il privilégier d'après Clear ?",
  ["Les objectifs plutôt que les systèmes",
   "Les résultats immédiats",
   "Les systèmes plutôt que les objectifs",
   "La motivation plutôt que la régularité"], 2,
  "Un objectif fixe une direction ; c'est le système quotidien qui produit le résultat."),
 ("À quoi Clear compare-t-il les habitudes ?",
  ["À un sprint",
   "À un talent inné",
   "À un coup de chance",
   "Aux intérêts composés"], 3,
  "Les habitudes sont les intérêts composés du développement personnel."),
],
3: [
 ("Sur quoi reposent les habitudes les plus durables ?",
  ["Sur l'identité que l'on adopte",
   "Sur le résultat chiffré visé",
   "Sur la seule force de volonté",
   "Sur une forte motivation de départ"], 0,
  "On tient une habitude quand elle exprime qui l'on est, pas seulement ce qu'on veut obtenir."),
 ("Quels sont les trois niveaux du changement ?",
  ["Signal, envie, récompense",
   "Objectifs, motivation, volonté",
   "Résultats, processus, identité",
   "Court, moyen et long terme"], 2,
  "Le changement le plus profond part de l'identité, puis irrigue processus et résultats."),
 ("Que représente chaque petite action selon Clear ?",
  ["Une corvée à subir",
   "Un vote pour la personne que l'on devient",
   "Une récompense immédiate",
   "Un objectif déjà atteint"], 1,
  "Chaque action est une preuve, un « vote » pour une identité."),
 ("Quelle est la façon la plus efficace d'ancrer un changement ?",
  ["Se fixer un résultat chiffré",
   "Se forcer par la seule volonté",
   "Copier les autres",
   "Adopter d'abord l'identité (« je suis quelqu'un qui… »)"], 3,
  "Partir de l'identité rend le comportement cohérent et naturel."),
],
4: [
 ("Quelles sont les quatre étapes de la boucle de l'habitude ?",
  ["Signal, envie, réponse, récompense",
   "Objectif, plan, effort, résultat",
   "Désir, volonté, action, repos",
   "Envie, doute, essai, échec"], 0,
  "Signal → envie → réponse → récompense : la boucle universelle de toute habitude."),
 ("Quel est le rôle du « signal » ?",
  ["Récompenser le comportement",
   "Déclencher le comportement en annonçant une récompense",
   "Mesurer le progrès",
   "Punir l'échec"], 1,
  "Le signal est l'amorce : il prédit une récompense et déclenche l'envie."),
 ("À quoi sert la « récompense » dans la boucle ?",
  ["À compliquer l'habitude",
   "À créer le signal",
   "À satisfaire l'envie et renforcer l'habitude",
   "À supprimer l'envie définitivement"], 2,
  "La récompense clôt la boucle et apprend au cerveau à recommencer."),
 ("À quoi sert de connaître cette boucle ?",
  ["À éviter toute habitude",
   "À mesurer son QI",
   "À prédire l'avenir",
   "À créer de bonnes habitudes et défaire les mauvaises, étape par étape"], 3,
  "Les quatre lois du livre agissent justement sur chacune de ces quatre étapes."),
],
5: [
 ("Quelle est la première condition pour changer une habitude ?",
  ["La rendre consciente",
   "La supprimer brutalement",
   "Augmenter sa motivation",
   "La remplacer par une récompense"], 0,
  "On ne peut transformer que ce que l'on a d'abord rendu conscient."),
 ("Que rappelle l'anecdote de l'« homme qui ne semblait pas avoir de mémoire » ?",
  ["Que la mémoire est inutile",
   "Que nos comportements deviennent automatiques et inconscients",
   "Qu'il faut tout noter",
   "Que l'oubli est une bonne habitude"], 1,
  "Beaucoup d'habitudes tournent en pilotage automatique, hors de notre conscience."),
 ("Quel outil ce chapitre propose-t-il ?",
  ["Un agenda partagé",
   "Une application de minuteur",
   "Lister ses habitudes et les qualifier de bonnes, mauvaises ou neutres",
   "Un tableau de récompenses"], 2,
  "La « carte de notation des habitudes » sort les automatismes du pilotage automatique."),
 ("Selon quoi juger qu'une habitude est bonne ou mauvaise ?",
  ["Selon l'avis des autres",
   "Selon sa difficulté",
   "Selon le plaisir immédiat",
   "Selon la personne que l'on veut devenir"], 3,
  "Une habitude est « bonne » si elle rapproche de l'identité visée."),
],
6: [
 ("Qu'est-ce qu'une « intention de mise en œuvre » ?",
  ["Préciser à l'avance quand et où accomplir l'habitude",
   "Espérer trouver le temps",
   "Se fixer un objectif annuel",
   "Demander la permission à quelqu'un"], 0,
  "« Je ferai [action] à [heure] à [lieu] » rend le passage à l'acte bien plus probable."),
 ("Qu'est-ce que l'empilement d'habitudes ?",
  ["Faire plusieurs habitudes en même temps",
   "Accrocher une nouvelle habitude à une habitude déjà automatique",
   "Empiler les objectifs",
   "Répéter une habitude sans pause"], 1,
  "On utilise une habitude existante comme signal d'une nouvelle."),
 ("Quelle est la formule de l'empilement d'habitudes ?",
  ["« Un jour je ferai X »",
   "« Si j'ai le temps, je ferai X »",
   "« Après [habitude actuelle], je ferai [nouvelle habitude] »",
   "« Je dois absolument faire X »"], 2,
  "L'habitude actuelle sert de déclencheur fiable à la nouvelle."),
 ("Pourquoi ces techniques fonctionnent-elles ?",
  ["Elles augmentent la volonté",
   "Elles suppriment l'envie",
   "Elles rendent l'habitude amusante",
   "Un signal clair et déjà automatique déclenche le comportement"], 3,
  "Un déclencheur précis enlève l'hésitation du « quand/où »."),
],
7: [
 ("Qu'est-ce qui déclenche nos comportements le plus puissamment ?",
  ["L'environnement",
   "La seule volonté",
   "Les conseils des experts",
   "La chance"], 0,
  "L'environnement et ses signaux pèsent souvent plus que la motivation."),
 ("Comment favoriser une bonne habitude par l'environnement ?",
  ["En cachant son signal",
   "En rendant son signal visible et accessible",
   "En attendant la motivation",
   "En la punissant"], 1,
  "Plus le bon signal saute aux yeux, plus l'habitude se déclenche."),
 ("Quelle idée clé résume ce chapitre ?",
  ["La motivation est tout ce qui compte",
   "Les signaux n'ont aucun effet",
   "Concevoir son espace change durablement ses actions",
   "Il faut déménager pour changer"], 2,
  "Façonner l'espace, c'est façonner le comportement."),
 ("Quelle action concrète propose ce chapitre ?",
  ["Supprimer tous ses objets",
   "Compter sur sa discipline",
   "Changer d'amis",
   "Placer le signal d'une bonne habitude bien en évidence"], 3,
  "Rendre le déclencheur omniprésent dans son espace de vie."),
],
8: [
 ("Que font surtout les personnes qui semblent avoir une grande maîtrise de soi ?",
  ["Elles suppriment les tentations de leur environnement plutôt que d'y résister",
   "Elles résistent en permanence par la volonté",
   "Elles n'ont jamais de tentations",
   "Elles se punissent sévèrement"], 0,
  "Elles organisent leur vie pour ne pas avoir à lutter."),
 ("Quelle est la stratégie pour défaire une mauvaise habitude (1re loi inversée) ?",
  ["Augmenter sa motivation",
   "Éliminer son signal de l'environnement",
   "La remplacer par une autre tentation",
   "La répéter jusqu'à s'en lasser"], 1,
  "Rendre le mauvais signal invisible coupe l'habitude à la racine."),
 ("Pourquoi résister à la tentation est-il inefficace sur la durée ?",
  ["Parce que c'est interdit",
   "Parce que cela rend l'habitude attirante",
   "Parce que la volonté s'épuise et le signal revient sans cesse",
   "Parce que cela coûte de l'argent"], 2,
  "Mieux vaut supprimer le signal que de s'épuiser à lui résister."),
 ("La première loi inversée consiste à rendre le signal…",
  ["Plus fréquent",
   "Plus agréable",
   "Plus fort",
   "Invisible"], 3,
  "Rendre invisible = première loi appliquée à l'envers."),
],
9: [
 ("Que dit la deuxième loi du changement ?",
  ["Rendre l'habitude attirante",
   "Rendre l'habitude difficile",
   "Rendre l'habitude invisible",
   "Rendre l'habitude lente"], 0,
  "Plus une habitude est désirable, plus on l'adopte."),
 ("Quel est le rôle de la dopamine dans l'habitude ?",
  ["Elle n'est libérée qu'après la récompense",
   "Elle est surtout libérée par l'anticipation de la récompense",
   "Elle bloque l'envie",
   "Elle n'a aucun rôle"], 1,
  "C'est l'anticipation, plus que la récompense elle-même, qui pousse à l'action."),
 ("En quoi consiste le « regroupement de tentations » ?",
  ["Cumuler les mauvaises habitudes",
   "Faire deux corvées à la suite",
   "Associer une habitude qu'on doit faire à une chose qu'on aime",
   "Repousser toutes les tentations"], 2,
  "On lie l'habitude voulue à un plaisir pour la rendre attirante."),
 ("Quelle action illustre cette loi ?",
  ["Supprimer tout plaisir",
   "Attendre la motivation",
   "Se forcer sans récompense",
   "Ne s'autoriser un plaisir qu'après avoir accompli l'habitude"], 3,
  "Le plaisir devient le moteur de l'habitude."),
],
10: [
 ("Par quoi nos habitudes sont-elles fortement façonnées ?",
  ["Par notre entourage et nos groupes d'appartenance",
   "Uniquement par nos gènes",
   "Par le hasard",
   "Par notre seule volonté"], 0,
  "Nous imitons les comportements de ceux qui nous entourent."),
 ("Qui imitons-nous le plus, selon Clear ?",
  ["Des inconnus lointains",
   "Les proches, la majorité et les personnes influentes",
   "Personne",
   "Uniquement nos rivaux"], 1,
  "Proches, tribu et figures de pouvoir orientent nos normes."),
 ("Comment rendre une habitude plus attirante grâce au social ?",
  ["S'isoler complètement",
   "Critiquer ceux qui la pratiquent",
   "Rejoindre un groupe où ce comportement est déjà la norme",
   "Attendre que les autres changent"], 2,
  "Quand l'habitude visée est la norme du groupe, elle devient naturelle."),
 ("Quelle action propose ce chapitre ?",
  ["Quitter tous ses amis",
   "Se comparer en permanence",
   "Imposer ses habitudes aux autres",
   "Rejoindre une tribu où l'habitude visée est normale"], 3,
  "L'appartenance rend le comportement désirable et durable."),
],
11: [
 ("À quoi répond toute habitude, en réalité ?",
  ["À un désir ou une motivation profonde sous-jacente",
   "À une obligation extérieure",
   "À rien de particulier",
   "À un ordre reçu"], 0,
  "Le comportement est une solution à un désir plus profond."),
 ("Qu'est-ce qui crée réellement l'envie ?",
  ["Le signal lui-même, mécaniquement",
   "L'interprétation/prédiction qu'on associe au signal",
   "La récompense uniquement",
   "Le hasard"], 1,
  "Le même signal peut être vécu autrement selon le sens qu'on lui donne — donc on peut le recadrer."),
 ("Comment rendre une mauvaise habitude repoussante (2e loi inversée) ?",
  ["En augmentant la récompense",
   "En la cachant aux autres",
   "En recadrant mentalement ses conséquences négatives",
   "En la pratiquant davantage"], 2,
  "Mettre en lumière le vrai coût d'une habitude réduit son attrait."),
 ("Quelle action illustre ce chapitre ?",
  ["Ignorer ses envies",
   "Augmenter les tentations",
   "Se récompenser pour une mauvaise habitude",
   "Lister les conséquences négatives réelles d'une mauvaise habitude"], 3,
  "Reformuler ses bénéfices/coûts change l'envie."),
],
12: [
 ("Quelle est la différence entre « se mettre en mouvement » et « agir » ?",
  ["Se préparer/planifier versus accomplir réellement l'habitude",
   "Marcher versus courir",
   "Penser versus rêver",
   "Il n'y a aucune différence"], 0,
  "Le « mouvement » prépare ; seule l'action produit un résultat."),
 ("Qu'est-ce qui crée la maîtrise selon ce chapitre ?",
  ["La perfection de chaque tentative",
   "La fréquence des répétitions",
   "Le temps passé à se préparer",
   "Le talent de départ"], 1,
  "On progresse par le nombre de répétitions, pas par la durée de préparation."),
 ("Quel est le piège du « mouvement » ?",
  ["Il fatigue trop",
   "Il coûte cher",
   "Il donne l'illusion de progresser sans agir",
   "Il rend l'habitude trop facile"], 2,
  "Planifier sans cesse peut devenir une forme de procrastination."),
 ("Quelle action propose ce chapitre ?",
  ["Attendre le bon moment",
   "Préparer un plan parfait",
   "Lire un livre de plus",
   "Accomplir l'habitude aujourd'hui, même imparfaitement"], 3,
  "Mieux vaut agir imparfaitement que se préparer indéfiniment."),
],
13: [
 ("Que dit la troisième loi du changement ?",
  ["Rendre l'habitude facile",
   "Rendre l'habitude attirante",
   "Rendre l'habitude invisible",
   "Rendre l'habitude satisfaisante"], 0,
  "Réduire l'effort nécessaire favorise la répétition."),
 ("Quel chemin le cerveau choisit-il naturellement ?",
  ["Le plus difficile",
   "Celui du moindre effort",
   "Le plus long",
   "Le plus risqué"], 1,
  "On gravite vers l'option qui demande le moins d'énergie."),
 ("Quelle est la stratégie de la loi du moindre effort ?",
  ["Augmenter la friction des bonnes habitudes",
   "Supprimer toute récompense",
   "Réduire la friction des bonnes habitudes et augmenter celle des mauvaises",
   "Tout automatiser sans réfléchir"], 2,
  "On facilite le bon comportement et on complique le mauvais."),
 ("Quelle action illustre ce chapitre ?",
  ["Ajouter des étapes à une bonne habitude",
   "Compter sur la motivation",
   "Cacher ses outils",
   "Préparer son environnement la veille pour qu'une bonne habitude soit immédiate"], 3,
  "Supprimer une étape de friction rend l'habitude quasi automatique."),
],
14: [
 ("En quoi consiste la règle des deux minutes ?",
  ["Réduire une nouvelle habitude à une version de moins de deux minutes",
   "Faire une pause de deux minutes",
   "Méditer deux minutes par jour",
   "Attendre deux minutes avant d'agir"], 0,
  "On ancre d'abord l'amorce, si facile qu'on ne peut la refuser."),
 ("Pourquoi commencer aussi petit ?",
  ["Pour économiser de l'argent",
   "Parce que maîtriser l'amorce garantit la régularité",
   "Pour impressionner les autres",
   "Parce que les grandes habitudes sont inutiles"], 1,
  "Un rituel d'entrée facile rend l'habitude répétable, puis on l'étend."),
 ("Quel exemple illustre la règle des deux minutes ?",
  ["« Courir un marathon » devient « s'inscrire à une course »",
   "« Lire un livre par semaine » devient « lire toute la soirée »",
   "« Lire chaque soir » devient « lire une page »",
   "« Manger sain » devient « suivre un régime strict »"], 2,
  "On réduit l'habitude à sa plus petite mise en route."),
 ("Quelle action propose ce chapitre ?",
  ["Tout faire d'un coup",
   "Reporter à demain",
   "Viser la perfection",
   "Définir et accomplir seulement la version « deux minutes » d'une habitude"], 3,
  "Maîtriser l'art de se présenter avant d'augmenter."),
],
15: [
 ("Qu'est-ce qu'un dispositif (ou contrat) d'engagement ?",
  ["Une décision prise maintenant qui contraint le comportement futur",
   "Une promesse vague",
   "Un objectif annuel",
   "Une récompense immédiate"], 0,
  "On verrouille à l'avance le bon choix pour qu'il s'impose plus tard."),
 ("Que dit la troisième loi inversée ?",
  ["Rendre l'habitude attirante",
   "Rendre la mauvaise habitude difficile",
   "Rendre l'habitude satisfaisante",
   "Rendre l'habitude visible"], 1,
  "Augmenter la friction d'une mauvaise habitude la décourage."),
 ("Quel est l'intérêt d'automatiser un bon comportement ?",
  ["Cela supprime toute habitude",
   "Cela augmente la tentation",
   "Un choix unique verrouille durablement le bon comportement",
   "Cela rend l'habitude invisible"], 2,
  "Ex. : un virement automatique rend l'épargne inévitable."),
 ("Quelle action propose ce chapitre ?",
  ["Compter sur sa volonté",
   "Attendre d'être prêt",
   "Rendre la mauvaise habitude plus accessible",
   "Mettre en place une automatisation ou un engagement qui rend le bon comportement inévitable"], 3,
  "On conçoit l'inévitabilité plutôt que d'espérer la discipline."),
],
16: [
 ("Que dit la quatrième loi du changement ?",
  ["Rendre l'habitude satisfaisante",
   "Rendre l'habitude facile",
   "Rendre l'habitude invisible",
   "Rendre l'habitude difficile"], 0,
  "Ce qui est immédiatement satisfaisant est répété."),
 ("Quel type de récompense le cerveau privilégie-t-il ?",
  ["La récompense très lointaine",
   "La récompense immédiate plutôt que différée",
   "Aucune récompense",
   "La punition"], 1,
  "Le cerveau humain valorise le présent : la récompense immédiate l'emporte."),
 ("Pourquoi les bonnes habitudes sont-elles difficiles à tenir ?",
  ["Elles sont trop faciles",
   "Elles n'ont aucun coût",
   "Leur coût est immédiat mais leurs bénéfices sont différés",
   "Elles sont toujours agréables"], 2,
  "Le déséquilibre coût immédiat / bénéfice lointain décourage."),
 ("Quelle solution propose ce chapitre ?",
  ["Supprimer la récompense",
   "Attendre les bénéfices lointains",
   "Augmenter la difficulté",
   "Ajouter une petite récompense immédiate à une bonne habitude"], 3,
  "On rend satisfaisant sur le moment ce qui paiera plus tard."),
],
17: [
 ("Pourquoi suivre (mesurer) ses habitudes aide-t-il ?",
  ["Cela rend le progrès visible et satisfaisant",
   "Cela complique l'habitude",
   "Cela remplace l'action",
   "Cela n'a aucun effet"], 0,
  "Voir sa progression est en soi une récompense qui motive."),
 ("Quelle est la « règle d'or » de la constance ?",
  ["Ne jamais se reposer",
   "Ne jamais manquer deux fois",
   "Ne jamais mesurer",
   "Ne jamais changer d'habitude"], 1,
  "Un écart isolé n'est pas grave ; c'est en manquer deux d'affilée qui amorce l'abandon."),
 ("Pourquoi cette règle est-elle importante ?",
  ["Parce qu'un seul écart ruine tout",
   "Parce qu'il faut être parfait",
   "Parce qu'un écart isolé n'est pas un échec, mais l'abandon en est un",
   "Parce que la mesure est inutile"], 2,
  "Rater une fois est humain ; reprendre tout de suite préserve l'habitude."),
 ("Quelle action propose ce chapitre ?",
  ["Abandonner après un oubli",
   "Tout recommencer de zéro",
   "Viser la perfection absolue",
   "Mettre en place un suivi visuel et reprendre dès le lendemain en cas d'oubli"], 3,
  "Un suivi simple + la règle « jamais deux fois » sécurisent la régularité."),
],
18: [
 ("Que dit la quatrième loi inversée ?",
  ["Rendre la mauvaise habitude insatisfaisante (voire douloureuse)",
   "Rendre l'habitude attirante",
   "Rendre l'habitude facile",
   "Rendre l'habitude invisible"], 0,
  "Une conséquence immédiate et désagréable décourage la mauvaise habitude."),
 ("Qu'est-ce qu'un contrat de comportement ?",
  ["Un objectif chiffré",
   "Un engagement qui attache une conséquence immédiate à un écart",
   "Une simple liste de tâches",
   "Une récompense automatique"], 1,
  "On rend le coût d'un relâchement immédiat et public."),
 ("Quel est le rôle d'un partenaire de responsabilité ?",
  ["Faire l'habitude à notre place",
   "Nous féliciter sans condition",
   "Nous tenir responsable et rendre le coût d'un écart immédiat",
   "Choisir nos objectifs"], 2,
  "Le regard d'autrui crée une conséquence sociale immédiate."),
 ("Quelle action propose ce chapitre ?",
  ["Cacher ses objectifs",
   "Agir seul sans rendre de comptes",
   "Supprimer toute conséquence",
   "Trouver un partenaire de responsabilité ou rédiger un contrat de comportement"], 3,
  "Rendre l'écart coûteux et visible aide à tenir."),
],
19: [
 ("Que déterminent surtout nos gènes, selon Clear ?",
  ["Nos domaines d'opportunité, pas notre destin",
   "Notre réussite garantie",
   "Notre échec inévitable",
   "Rien du tout"], 0,
  "Les gènes orientent vers des terrains où l'on progresse plus facilement."),
 ("Quelle stratégie en découle ?",
  ["Combattre sa nature à tout prix",
   "Choisir des habitudes et des terrains alignés sur sa nature",
   "Copier les habitudes des autres",
   "Ignorer ses points forts"], 1,
  "On gagne à jouer un jeu où l'on est naturellement avantagé."),
 ("Que signifie « le talent ne fixe pas tout » ici ?",
  ["Le talent rend l'effort inutile",
   "Le talent n'existe pas",
   "Les gènes fixent des prédispositions, mais le travail décide de l'exploitation",
   "Seul le talent compte"], 2,
  "Les prédispositions ouvrent des portes ; les habitudes les franchissent."),
 ("Quelle action propose ce chapitre ?",
  ["Imiter le parcours d'un autre",
   "Choisir l'activité la plus prestigieuse",
   "Travailler ses plus grandes faiblesses d'abord",
   "Bâtir une habitude autour d'une force naturelle où l'on progresse vite"], 3,
  "On construit sur ses avantages plutôt que de lutter contre soi."),
],
20: [
 ("Que dit la « règle de Boucle d'or » ?",
  ["La motivation est maximale à un niveau de difficulté juste, ni trop facile ni trop dur",
   "Il faut toujours choisir le plus difficile",
   "Il faut rester dans le plus facile",
   "La difficulté n'a aucun effet"], 0,
  "Le « juste assez dur » entretient l'engagement."),
 ("Quel est le plus grand obstacle à la maîtrise sur la durée ?",
  ["Le manque de talent",
   "L'ennui",
   "Le manque d'argent",
   "Le manque d'information"], 1,
  "La vraie difficulté est de persévérer quand la nouveauté disparaît."),
 ("Qu'est-ce qui distingue les pros des amateurs, selon ce chapitre ?",
  ["Les pros n'ont jamais d'ennui",
   "Les amateurs travaillent plus",
   "Les pros continuent même quand c'est ennuyeux",
   "Les pros changent souvent d'objectif"], 2,
  "La constance malgré l'ennui fait la différence."),
 ("Quelle action propose ce chapitre ?",
  ["Rendre l'habitude beaucoup plus facile",
   "Abandonner dès l'ennui",
   "Chercher toujours plus de nouveauté",
   "Garder l'habitude juste à la lisière de ses capacités et la poursuivre même les jours sans envie"], 3,
  "On ajuste la difficulté et on tient malgré la monotonie."),
],
21: [
 ("Quel est le revers de l'automatisme des habitudes ?",
  ["Il peut figer le progrès et installer des erreurs",
   "Il rend toujours plus performant",
   "Il supprime toute habitude",
   "Il n'a aucun inconvénient"], 0,
  "À force d'automatiser, on cesse de remarquer ce qui pourrait s'améliorer."),
 ("Quel remède propose Clear face à ce revers ?",
  ["Arrêter toutes ses habitudes",
   "La réflexion et la révision régulières",
   "Ajouter sans cesse de nouvelles habitudes",
   "Ignorer ses résultats"], 1,
  "Un examen régulier permet de corriger la dérive et de continuer à progresser."),
 ("Pourquoi combiner habitudes et révision délibérée ?",
  ["Pour rendre les habitudes inconscientes définitivement",
   "Pour supprimer la pratique",
   "Pour garder l'efficacité de l'automatisme tout en restant capable de s'améliorer",
   "Pour travailler moins"], 2,
  "L'automatisme libère l'esprit ; la révision empêche la stagnation."),
 ("Quelle action propose ce chapitre ?",
  ["Ne jamais se remettre en question",
   "Changer d'habitude chaque jour",
   "Se comparer aux autres en permanence",
   "Planifier un moment régulier de bilan de ses habitudes"], 3,
  "Un rituel de révision entretient l'amélioration continue."),
],
22: [
 ("Quel est le « secret » des grands résultats, selon la conclusion ?",
  ["Il n'y a pas de secret : de petites habitudes maintenues avec patience",
   "Un talent exceptionnel",
   "Un changement radical unique",
   "Beaucoup de chance"], 0,
  "Les grands résultats sont la somme de petites habitudes tenues longtemps."),
 ("Quel rôle joue la patience ?",
  ["Elle est inutile",
   "Faire confiance à l'effet cumulatif plutôt qu'aux résultats immédiats",
   "Attendre sans rien faire",
   "Remplacer l'action"], 1,
  "Les progrès s'accumulent en coulisses : il faut tenir jusqu'au franchissement du seuil."),
 ("Qu'est-ce qui ancre le plus durablement une habitude ?",
  ["La récompense matérielle",
   "La pression sociale",
   "L'identité à laquelle elle est reliée",
   "La nouveauté permanente"], 2,
  "Une habitude reliée à « qui je suis » se maintient d'elle-même."),
 ("Quelle action propose la conclusion ?",
  ["Multiplier les objectifs",
   "Tout changer en une semaine",
   "Chercher des raccourcis",
   "Maintenir une seule habitude atomique chaque jour pendant des mois"], 3,
  "On laisse l'accumulation faire son œuvre, sans précipitation."),
],
}

path = Path("public/books/atomic-habits.json")
data = json.loads(path.read_text(encoding="utf-8"))

for card in data["cards"]:
    n = card["order"]
    qs = Q.get(n)
    assert qs, f"Pas de questions pour la carte {n}"
    out = []
    for i, (question, choices, ans, expl) in enumerate(qs, start=1):
        assert len(choices) == 4, f"carte {n} q{i}: {len(choices)} choix"
        assert 0 <= ans < 4, f"carte {n} q{i}: answerIndex {ans}"
        out.append({
            "id": f"{card['id']}-q{i}",
            "question": question,
            "choices": choices,
            "answerIndex": ans,
            "explanation": expl,
        })
    card["questions"] = out

path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
total = sum(len(c["questions"]) for c in data["cards"])
print(f"OK : {len(data['cards'])} cartes, {total} questions injectées.")
